name: bom_hamburguer
description: "Bom hamburguer app"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  get_it: 8.0.3
  go_router: 16.0.0
  dio: 5.8.0+1
  shared_preferences: 2.5.2
  full_coverage: 1.0.0
  firebase_auth: 5.6.2
  connectivity_plus: 6.1.4
  in_app_purchase: 3.2.3
  flutter_secure_storage: 9.2.4
  firebase_remote_config: 5.4.7

  design_system:
    path: ./packages/design_system
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  change_app_package_name: 1.2.0
  melos: 6.3.2

flutter:
  uses-material-design: true
