name: bom_hamburguer
description: "Bom hamburguer app"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  go_router: 16.0.0

  design_system:
    path: ./packages/design_system
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  change_app_package_name: 1.2.0
  melos: 6.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/categories_data.json
